version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file LambdaParagraphLinker.yaml --s3-bucket onlaw
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml