
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file ./lambdas/paragraphlinker/LambdaParagraphLinker.yaml --s3-bucket onlaw
                                   --output-template-file NewSamTemplate.yaml --region eu-west-1
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
