AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Identifies paragraphs in documents and links to the law
Resources:
  LambdaParagraphLinker:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: Identifies paragraphs in documents and links to the law
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::681075711895:role/service-role/ParagraphLinkerRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /LambdaParagraphLinker
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python3
